<?php

namespace Jimaoxiaoxin\VisaWorkflowEngine\Providers;

use Illuminate\Support\ServiceProvider;
class WorkflowEngineServiceProvider extends ServiceProvider {

    public function boot()
    {
        $this->publishes([
            __DIR__.'/../config/workflow-engine.php' => config_path('workflow-engine.php'),
        ]);
        $this->loadRoutesFrom(__DIR__.'/../routes/workflow-engine.php');
        $this->loadMigrationsFrom(__DIR__.'/../database/migrations');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
